routes/web.php
<?php

Route::get('/', 'HomeController@index');

Route::group(['prefix' => 'auth'], function () {
    Route::view('login', 'auth.login')->name('login');
    Route::post('login', 'Auth\LoginController@login')->name('login');
    Route::post('logout', 'Auth\LoginController@logout');
    Route::view('reg', 'auth.reg');
    Route::post('reg', 'Auth\RegisterController@register');
    Route::view('forget', 'auth.forget');
    Route::post('forget', 'Auth\ForgotPasswordController@sendResetLinkEmail');
    Route::get('reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('reset', 'Auth\ResetPasswordController@reset');
    Route::any('captcha', 'AuthController@captcha');
});

Route::group([], function () {
    Route::get('search', 'BookController@list');

    Route::group(['prefix' => 'book'], function () {
        Route::get('{id}', 'BookController@detail');
        Route::post('{id}/comment', 'BookController@comment')->middleware('auth');
    });
});

Route::group(['prefix' => 'shoppingCart', 'middleware' => 'auth'], function () {
    Route::view('', 'shoppingCart.list');
    Route::get('list', 'ShoppingCartController@list');
    Route::post('add', 'ShoppingCartController@add');
    Route::post('remove', 'ShoppingCartController@remove');
    Route::post('decrement', 'ShoppingCartController@decrement');
    Route::post('set', 'ShoppingCartController@setAmount');
});

Route::group(['prefix' => 'user', 'middleware' => 'auth'], function () {
    Route::redirect('', 'user/orders');

    Route::group(['prefix' => 'orders'], function () {
        Route::get('', 'OrdersController@index');
        Route::get('{id}', 'OrdersController@detail');
        Route::post('cancel', 'OrdersController@cancel');
    });

    Route::group(['prefix' => 'favorites'], function () {
        Route::view('', 'user.favorites');
        Route::get('list', 'FavoriteController@list');
        Route::post('add', 'FavoriteController@add');
        Route::post('remove', 'FavoriteController@remove');
    });

    Route::group(['prefix' => 'address'], function () {
        Route::view('', 'user.address');
        Route::get('list', 'AddressController@list');
        Route::post('add', 'AddressController@add');
        Route::post('update', 'AddressController@update');
        Route::post('remove', 'AddressController@remove');
    });

    Route::group(['prefix' => 'account'], function () {
        Route::view('', 'user.account');
        Route::post('password', 'AccountController@password');
        Route::post('delete', 'AccountController@delete');
    });
});

Route::group(['prefix' => 'pay'], function () {
    Route::post('notify', 'PaymentController@notify'); // DO NOT add `auth` middleware.

    Route::group(['middleware' => 'auth'], function () {
        Route::any('prepare', 'PaymentController@prepare');
        Route::post('send', 'PaymentController@send');
        Route::get('return', 'PaymentController@return');
    });
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::view('', 'admin.base');

    Route::group(['prefix' => 'users'], function () {
        Route::get('list', 'UsersManagementController@list');
        Route::post('update', 'UsersManagementController@update');
        Route::post('remove', 'UsersManagementController@remove');
    });

    Route::group(['prefix' => 'books'], function () {
        Route::get('list', 'BooksManagementController@list');
        Route::get('info', 'BooksManagementController@info');
        Route::post('add', 'BooksManagementController@add');
        Route::post('update', 'BooksManagementController@update');
        Route::post('cover', 'BooksManagementController@cover');
        Route::post('remove', 'BooksManagementController@remove');
    });

    Route::group(['prefix' => 'categories'], function () {
        Route::get('list', 'CategoriesManagementController@list');
        Route::get('tree', 'CategoriesManagementController@tree');
        Route::get('all-trees', 'CategoriesManagementController@allTrees');
        Route::get('ancestors', 'CategoriesManagementController@ancestors');
        Route::post('add', 'CategoriesManagementController@add');
        Route::post('update', 'CategoriesManagementController@update');
        Route::post('remove', 'CategoriesManagementController@remove');
    });

    Route::group(['prefix' => 'orders'], function () {
        Route::get('list', 'OrdersManagementController@list');
        Route::get('books', 'OrdersManagementController@books');
        Route::post('update', 'OrdersManagementController@update');
        Route::post('cancel', 'OrdersManagementController@cancel');
    });

    Route::group(['prefix' => 'comments'], function () {
        Route::get('list', 'CommentsManagementController@list');
        Route::post('content', 'CommentsManagementController@content');
        Route::post('rating', 'CommentsManagementController@rating');
        Route::post('delete', 'CommentsManagementController@delete');
    });
});

Route::group(['prefix' => 'faq'], function () {
    Route::group(['prefix' => 'Buy'], function () {
        Route::view('peison', 'faq.buy.peison');
    });

    Route::group(['prefix' => 'otherInfo'], function () {
        Route::view('about', 'faq.otherInfo.about');
    });

    Route::group(['prefix' => 'toNews'], function () {
        Route::view('price', 'faq.toNews.price');
        Route::view('question', 'faq.toNews.question');
        Route::view('buy','faq.toNews.buy');
    });
});

Route::group(['prefix' => 'subjects'], function () {
    Route::view('bestSelling','subjects.bestSelling');
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $casts = [
        'price' => 'float',
        'amount' => 'integer',
        'publish_time' => 'date:Y-m-d',
    ];

    protected $fillable = [
        'name', 'price', 'amount', 'author', 'isbn',
        'publisher', 'publish_time', 'category_id',
        'img', 'description', 'detail',
    ];

    public function getPublishDateAttribute()
    {
        return $this->publish_time->toDateString();
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use DB;
use Cache;
use App\Models\Book;
use App\Models\Comment;
use App\Models\Category;
use Illuminate\Http\Request;

class BookController extends Controller
{
    public function list(Request $request, Book $books)
    {
        $keyword = $request->input('q');
        if ($keyword) {
            $keywords = explode(' ', $keyword);
            $books = $books->where(function ($query) use ($keywords) {
                foreach ($keywords as $keyword) {
                    $query->orWhere('name', 'LIKE', "%$keyword%");
                }
            });
        }

        $author = $request->input('author');
        if ($author) {
            $books = $books->where('author', $author);
        }

        $publisher = $request->input('publisher');
        if ($publisher) {
            $books = $books->where('publisher', $publisher);
        }

        $categoryId = $request->input('category');
        if ($categoryId) {
            $category = Category::find($categoryId);
            if ($category) {
                $categories = $category
                    ->childrenTree()
                    ->flatten()
                    ->unique()
                    ->pluck('id')
                    ->all();
            } else {
                $categories = [];
            }

            $books = $books->whereIn('category_id', $categories);
        }

        $books = $books->paginate(10);
        $user = $request->user();

        return view('book.list', [
            'books' => $books,
            'user' => $user,
            'favorites' => $user ? $user->favorites : collect(),
        ]);
    }

    public function detail($id)
    {
        $book = Cache::rememberForever('book_model-'.$id, function () use ($id) {
            return Book::findOrFail($id);
        });
        $category = $book->category;
        if (empty($category)) {
            $categories = collect();
        } else {
            $categories = $category->ancestors()->reverse()->values();
        }

        $user = auth()->user();
        if ($user) {
            $favored = $user->favorites->contains($id);
        } else {
            $favored = false;
        }

        $ratingLabels = [
            'bad' => '差评',
            'medium' => '中评',
            'good' => '好评',
        ];
        $comments = $book
            ->comments()
            ->paginate(10)
            ->setPageName('comment-page');

        $canComment = auth()->check() &&
            DB::table('book_order')
                ->where('book_id', $book->id)
                ->where('user_id', $user->id)
                ->exists() &&
            ! $comments->contains(function ($comment) use ($user) {
                return $comment->user_id === $user->id;
            });

        return view('book.detail', [
            'book' => $book,
            'categories' => $categories,
            'ratingLabels' => $ratingLabels,
            'comments' => $comments,
            'canComment' => $canComment,
            'favored' => $favored,
            'youMayLike' => $this->guessYouMayLike(),
        ]);
    }

    public function guessYouMayLike($amount = 5)
    {
        return Book::inRandomOrder()->take($amount)->get();
    }

    public function comment(Request $request, $id)
    {
        $data = $this->validate($request, [
            'content' => 'required|string',
            'rating' => 'required|in:bad,medium,good',
        ]);

        $comment = new Comment();
        $comment->user_id = auth()->id();
        $comment->book_id = $id;
        $comment->content = $data['content'];
        $comment->rating = $data['rating'];
        $comment->save();

        return back()->with('open-comments', true);
    }
}

resources/views/book/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title') | 中国淘书网</title>
    <link rel="stylesheet" href="{{ mix('/css/rightNav.css') }}">
    @yield('css')
</head>
<body>
    @include('common.header')

    <section class="content">
        @yield('content')
    </section>

    @include('common.rightNav')
    @include('common.footer')

    @yield('js')
</body>
</html>

resources/views/book/detail.blade.php
@extends('book.base')

@section('title', $book->name)

@section('css')
<link rel="stylesheet" href="{{ mix('/css/detail.css') }}">
@endsection

@section('content')
<div class="breadcrumb">
    <div class="breadcrumb-item">
        <a href="/">中国淘书网</a>
    </div>
    <div class="breadcrumb-item separator">
        <i class="el-icon-arrow-right"></i>
    </div>
    @foreach ($categories as $category)
        <div class="breadcrumb-item">
            <a href="/search?category={{ $category['id'] }}">
                {{ $category['name'] }}
            </a>
        </div>
        <div class="breadcrumb-item separator">
            <i class="el-icon-arrow-right"></i>
        </div>
    @endforeach
    <div class="breadcrumb-item">{{ $book->name }}</div>
</div>
<div class="detail">
    <div class="book-img">
        <img src="{{ $book->img }}" alt="{{ $book->name }}">
    </div>
    <div class="book-info">
        <h1 class="book-name">{{ $book->name }}</h1>
        <div class="book-meta">
            <p>
                作者：
                <a href="/search?author={{ $book->author }}">
                    {{ $book->author }}
                </a>
            </p>
            <p>
                出版社：
                <a href="/search?publisher={{ $book->publisher }}">
                    {{ $book->publisher }}
                </a>
            </p>
            <p>出版时间：{{ $book->publish_time->format('Y-m-d') }}</p>
            <p>
                价格：<span class="price">￥{{ $book->price }}</span>
            </p>
        </div>
        <div class="actions">
            <button id="to-cart">加入购物车</button>
            <button id="to-fav" data-fav="{{ $favored ? 'true' : '' }}">
                {{ $favored ? '取消收藏' : '收藏' }}
            </button>
        </div>
    </div>
</div>

@php
    $openComments = session()->pull('open-comments');
@endphp
<section class="main-content">
    <div class="book-detail">
        <div data-selected="detail" class="book-tab">
            <div class="{{ $openComments ? '' : 'active' }}">图书详情</div>
            <div class="{{ $openComments ? 'active' : '' }}">评论</div>
        </div>

        <div class="detail-content {{ $openComments ? 'hidden' : '' }}">
            {!! $book->detail !!}
        </div>

        <div class="comments {{ $openComments ? '' : 'hidden' }}">
            <ul class="comments-list">
                @foreach ($comments as $comment)
                    <li>
                        <p class="meta">
                            {{ $comment->author ? $comment->author->username : '账号已注销' }}：
                            <span class="rating-{{ $comment->rating }}">
                                {{ $ratingLabels[$comment->rating] }}
                            </span>
                        </p>
                        <p class="comment-content">
                            @foreach(explode("\n", $comment->content) as $line)
                                {{ $line }}<br>
                            @endforeach
                        </p>
                        <p><time>{{ $comment->created_at }}</time></p>
                    </li>
                @endforeach
            </ul>
            @if ($canComment)
                <form action="/book/{{ $book->id }}/comment" method="post">
                    <p class="heading">添加评论：</p>
                    @csrf
                    <textarea name="content" rows="6"></textarea>
                    <div class="ratings">
                        评价：
                        <label>
                            <input type="radio" name="rating" value="bad">
                            <span class="rating-bad">差评</span>
                        </label>
                        <label>
                            <input type="radio" name="rating" value="medium">
                            <span class="rating-medium">中评</span>
                        </label>
                        <label>
                            <input type="radio" name="rating" value="good" checked="checked">
                            <span class="rating-good">好评</span>
                        </label>
                    </div>
                    <input type="submit" value="提交">
                    @if ($errors->any())
                        <div class="errors">{{ $errors->first() }}</div>
                    @endif
                </form>
            @endif
        </div>
    </div>
</section>

<div class="you-may-like">
    <div class="title">猜您喜欢</div>
    <ul>
        @foreach ($youMayLike as $book)
            <li>
                <a href="/book/{{ $book->id }}" target="_blank">
                    <img src="{{ $book->img }}" alt="{{ $book->name }}">
                    <p class="book-name">{{ $book->name }}</p>
                    <p class="author">{{ $book->author }} 著</p>
                    <p class="price">￥{{ $book->price }}</p>
                </a>
                <button class="to-cart" data-book-id="{{ $book->id }}">
                    加入购物车
                </button>
            </li>
        @endforeach
    </ul>
</div>
@endsection

@section('js')
<script src="{{ mix('/js/book-detail.js') }}"></script>
@endsection

resources/views/book/list.blade.php
@extends('book.base')

@section('title', '搜索结果')

@section('css')
<link rel="stylesheet" href="{{ mix('/css/list.css') }}" />
@endsection

@section('content')
<ul class="books-list">
    @foreach ($books as $book)
    <li>
        <div class="cover">
            <img src="{{ $book->img }}" alt="{{ $book->name }}">
        </div>
        <div>
            <div>
                <a class="book-name" href="/book/{{ $book->id }}" target="_blank">
                    {{ $book->name }}
                </a>
            </div>
            <div class="book-info">
                <div>
                    <div class="book-meta">
                        {{ $book->author }} / {{ $book->publish_date }} / {{ $book->publisher }}
                    </div>
                    <div class="price">￥{{ $book->price }}</div>
                    <div class="description">{{ $book->description }}</div>
                </div>
                <div>
                    <button class="btn btn-add-to-cart" data-book-id="{{ $book->id }}">
                        放入购物车
                    </button>
                    &nbsp;&nbsp;
                    @if ($favorites->contains($book->id))
                        <button class="btn btn-fav" data-book-id="{{ $book->id }}" data-fav="true">
                            取消收藏
                        </button>
                    @else
                        <button class="btn btn-fav" data-book-id="{{ $book->id }}">收藏</button>
                    @endif
                </div>
            </div>
        </div>
    </li>
    @endforeach
</ul>

<div>
    {{ $books->links() }}
</div>
@endsection

@section('js')
<script src="{{ mix('/js/books-list.js') }}"></script>
@endsection